services:
  - type: web
    name: nexus-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BACKEND_URL
        value: https://nexus-event-management-web.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: KHALTI_ENV
        value: sandbox
      - key: KHALTI_SECRET_KEY
        sync: false
      - key: KHALTI_PUBLIC_KEY
        sync: false
      - key: ESEWA_ENV
        value: sandbox
      - key: ESEWA_MERCHANT_ID
        sync: false
      - key: ESEWA_SECRET_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM_ADDRESS
        sync: false
      - key: EMAIL_FROM_NAME
        value: Nexus Events
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
